services:
  api:
    image: alpine
    command: ["sh", "-c", "echo api placeholder"]

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  auth-service:
    build: ./auth-service
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongo
    ports:
      - "4010:4010"
    restart: unless-stopped

  iam-service:
    build: ./iam-service
    env_file:
      - ./iam-service/.env
    depends_on:
      - mongo
    ports:
      - "4010:4010"
    restart: unless-stopped

  chat-service:
    build: ./chat-service
    env_file:
      - ./chat-service/.env
    depends_on:
      - mongo
    ports:
      - "4020:4020"
    restart: unless-stopped


volumes:
  mongo_data:
